#!/bin/sh
#
# Simple cp command wrapper for robinhood
#

VERB=$1
SRC=$2
DEST=$3

BIN=`basename $0`

if [[ -z "$VERB" || -z "$SRC" || -z "$DEST" ]]; then
	echo "Usage:"
	echo "	$BIN ARCHIVE <src> <dest>"
	echo "	$BIN RESTORE <src> <dest>"
	exit 22
fi

if [[ $VERB == "ARCHIVE" || $VERB == "RESTORE" ]]; then

	cp -a "$SRC" "$DEST"
	exit $?
fi
